# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mq7-0I-yDVjcXs1UTkAM1LpRyw-btvrb
"""



from google.colab import drive
import os
import csv
import pandas as pd

# 1. CONEXÃO COM O DRIVE
drive.mount('/content/drive')

# 2. DEFINIÇÃO DA PASTA E ARQUIVO
# Certifique-se de que a pasta 'MeusLeads' existe no seu Drive, ou o código cria uma
pasta_no_drive = '/content/drive/MyDrive/MeusLeads'
if not os.path.exists(pasta_no_drive):
    os.makedirs(pasta_no_drive)

caminho_arquivo = os.path.join(pasta_no_drive, 'leads_imobiliaria.csv')

# 3. A FUNÇÃO ATUALIZADA (Agora ela aceita o 'caminho_do_arquivo')
def salvar_lead_csv(resultado_processamento, arquivo_destino):
    dados_para_salvar = {
        "score": resultado_processamento['score'],
        "temperatura": resultado_processamento['temperatura'],
        "dossie": resultado_processamento['dossie']
    }

    arquivo_existe = os.path.isfile(arquivo_destino)

    with open(arquivo_destino, mode='a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=dados_para_salvar.keys())

        if not arquivo_existe:
            writer.writeheader()

        writer.writerow(dados_para_salvar)

    print(f"✅ Lead salvo com sucesso em: {arquivo_destino}")

# 4. Nova função para filtrar leads por temperatura
def filtrar_leads_por_temperatura(arquivo_origem, temperatura):
    try:
        df = pd.read_csv(arquivo_origem)
        leads_filtrados = df[df['temperatura'].str.upper() == temperatura.upper()]
        if not leads_filtrados.empty:
            print(f"Leads com temperatura '{temperatura.upper()}':")
            display(leads_filtrados)
        else:
            print(f"Nenhum lead encontrado com temperatura '{temperatura.upper()}'.")
    except FileNotFoundError:
        print(f"Erro: Arquivo '{arquivo_origem}' não encontrado.")
    except Exception as e:
        print(f"Ocorreu um erro ao filtrar os leads: {e}")

# 5. TESTE (Para você ver funcionando agora)
# Supondo que você já tenha o resultado do processar_lead:
# resultado = processar_lead("Exemplo de lead para salvar")

# Aqui é onde você usa a função passando o caminho:
# salvar_lead_csv(resultado, caminho_arquivo)

def remover_duplicadas_csv(arquivo_origem):
    try:
        df = pd.read_csv(arquivo_origem)
        # Identifica e remove linhas duplicadas
        df_limpo = df.drop_duplicates()

        if len(df) > len(df_limpo):
            df_limpo.to_csv(arquivo_origem, index=False, encoding='utf-8')
            print(f"✅ Duplicatas removidas. Arquivo atualizado: {arquivo_origem}. {len(df) - len(df_limpo)} linhas duplicadas foram removidas.")
        else:
            print(f"ℹ️ Nenhuma duplicata encontrada no arquivo: {arquivo_origem}.")
    except FileNotFoundError:
        print(f"Erro: Arquivo '{arquivo_origem}' não encontrado.")
    except Exception as e:
        print(f"Ocorreu um erro ao remover duplicatas: {e}")

# --- TESTE DA FUNÇÃO DE FILTRAGEM POR TEMPERATURA ---
# Exemplo de uso:
print("\n--- Filtrando leads com temperatura QUENTE ---")
filtrar_leads_por_temperatura(caminho_arquivo, "QUENTE")

print("\n--- Filtrando leads com temperatura MORNO ---")
filtrar_leads_por_temperatura(caminho_arquivo, "MORNO")

print("\n--- Filtrando leads com temperatura FRIO ---")
filtrar_leads_por_temperatura(caminho_arquivo, "FRIO")

print("\n--- Filtrando leads com temperatura inexistente (exemplo) ---")
filtrar_leads_por_temperatura(caminho_arquivo, "GELADO")



!pip install -q -U google-generativeai pydantic==2.12.3

"""To use the Gemini API securely, store your API key in Colab's secrets manager. Click the "🔑" icon on the left panel, create a new secret named `GOOGLE_API_KEY`, and paste your API key there. Then, run the following code to load it as an environment variable."""

import os
from google.colab import userdata

# This will load the GOOGLE_API_KEY from Colab's secrets manager into the environment
os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

import google.generativeai as genai
from pydantic import BaseModel, Field
from typing import List
import json
import os

# Configure sua chave API (O ambiente lerá a variável do Google AI Studio)
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))


# 1. Definindo a estrutura de dados (O contrato)
class LeadScoring(BaseModel):
    motivo_mudanca: str = Field(description="Resumo do evento de vida do usuário")
    urgencia: str = Field(description="Classificação: alta, media ou baixa")
    capacidade_financeira: str = Field(description="Classificação: alta, media ou baixa")
    tags: List[str] = Field(description="Interesses específicos, ex: varanda, pet-friendly")

# 2. Configurando o modelo para forçar saída em JSON (O segredo do MVP profissional)
# Trocando para um modelo flash disponível que encontramos: 'gemini-3.5-flash'
model = genai.GenerativeModel(
    model_name="gemini-3.5-flash",
    generation_config={"response_mime_type": "application/json"}
)

# 3. Função de Extração Inteligente
def extrair_dados_do_lead(historico_conversa):
    prompt = f"""
    Analise a conversa abaixo e extraia os dados do lead conforme o schema JSON solicitado.

    Conversa:
    {historico_conversa}

    Extraia apenas o JSON.
    """

    # Pedimos ao modelo para seguir o schema do Pydantic
    response = model.generate_content(
        prompt,
        generation_config={
            "response_mime_type": "application/json",
            "response_schema": LeadScoring,
        },
    )
    return json.loads(response.text)

# --- TESTE DO MOTOR ---
historico_teste = "Usuário: Quero me mudar logo porque vou casar em 3 meses. Procuro algo com varanda e escritório para trabalhar."
dados = extrair_dados_do_lead(historico_teste)

print("Dados Extraídos e Estruturados:")
print(json.dumps(dados, indent=2, ensure_ascii=False))

# 1. Nosso Estoque de Imóveis (Simulando um banco de dados real)
estoque = [
    {"id": 1, "titulo": "Apto com Varanda Gourmet", "tags": ["varanda", "escritorio"], "preco": 450000},
    {"id": 2, "titulo": "Studio compacto", "tags": ["compacto"], "preco": 250000},
    {"id": 3, "titulo": "Cobertura Luxo", "tags": ["varanda", "piscina"], "preco": 900000}
]

# 2. Função de Recomendação (O "Cérebro" do Match)
def recomendar_imoveis(dados_lead, estoque):
    sugestoes = []

    # Lógica de Match: Procura imóveis que tenham pelo menos uma das tags do lead
    for imovel in estoque:
        # Se as tags do lead (do JSON) estiverem nas tags do imóvel
        if any(tag in imovel['tags'] for tag in dados_lead['tags']):
            sugestoes.append(imovel)

    return sugestoes

# 3. Executando a lógica com os dados que extraímos anteriormente
sugestoes_reais = recomendar_imoveis(dados, estoque)

print(f"Sugestões encontradas para o perfil do lead:")
for s in sugestoes_reais:
    print(f"- {s['titulo']} (Preço: R$ {s['preco']})")

def calcular_lead_score(dados_lead):
    score = 0
    # Regra de Urgência (peso maior)
    if dados_lead['urgencia'] == "alta": score += 50
    elif dados_lead['urgencia'] == "media": score += 25

    # Regra de Capacidade Financeira
    if dados_lead['capacidade_financeira'] == "alta": score += 40
    elif dados_lead['capacidade_financeira'] == "media": score += 20

    return score

def gerar_dossie_corretor(dados_lead, sugestoes, score):
    dossie = f"""
    --- DOSSIÊ DO LEAD PARA CORRETOR ---
    SCORE DE QUALIFICAÇÃO: {score}/100

    MOTIVAÇÃO: {dados_lead['motivo_mudanca']}
    STATUS DE URGÊNCIA: {dados_lead['urgencia'].upper()}
    CAPACIDADE FINANCEIRA: {dados_lead['capacidade_financeira'].upper()}
    INTERESSES CHAVE (TAGS): {', '.join(dados_lead['tags'])}

    SUGESTÕES DE IMÓVEIS (MATCH):
    """
    for s in sugestoes:
        dossie += f"- {s['titulo']} (R$ {s['preco']})\n"

    return dossie

# --- TESTE FINAL ---
score_final = calcular_lead_score(dados)
dossie_final = gerar_dossie_corretor(dados, sugestoes_reais, score_final)

print(dossie_final)

import google.generativeai as genai
from pydantic import BaseModel, Field
from typing import List
import json
import os

# SUBSTITUA PELA SUA CHAVE REAL AQUI
api_key = os.getenv("GOOGLE_API_KEY")

try:
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-1.5-flash")

    class LeadScoring(BaseModel):
        motivo_mudanca: str
        urgencia: str
        capacidade_financeira: str
        tags: List[str]

    # Teste de conexão simples
    print("Testando conexão com o Gemini...")
    response = model.generate_content("Responda apenas 'Ok'")
    print("Conexão bem-sucedida:", response.text.strip())

    # Agora a função de extração
    def extrair_dados_do_lead(historico):
        prompt = f"Analise: '{historico}'. Responda APENAS com um JSON puro seguindo este schema: {LeadScoring.schema_json()}"
        response = model.generate_content(prompt)
        # Limpeza para garantir que venha só o JSON
        raw_text = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(raw_text)

    # Execução
    historico_teste = "Quero me mudar logo porque vou casar em 3 meses. Procuro algo com varanda e escritório."
    dados = extrair_dados_do_lead(historico_teste)
    print("\nSucesso! 'dados' foi criado:", dados)

except Exception as e:
    print(f"\n--- Ocorreu um erro! ---\n{e}")

!pip install -q -U google-generativeai

import google.generativeai as genai
import os

# Certifique-se de configurar a chave antes
genai.configure(api_key=os.getenv("GOOGLE_API_KEY")) # Verifique se esta é a chave API correta e válida

# Vamos listar os modelos disponíveis para verificar quais sua chave API pode acessar.
print("Listando modelos disponíveis:")
for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

import google.generativeai as genai
from pydantic import BaseModel, Field
from typing import List
import json
import os

# --- 1. CONFIGURAÇÃO ---
genai.configure(api_key=os.getenv("GOOGLE_API_KEY")) # Usando a chave já presente no notebook
model = genai.GenerativeModel('gemini-3.5-flash') # Mantendo o modelo 'gemini-3.5-flash' que está funcionando

# --- 2. CONFIGURAÇÃO DE NEGÓCIO (Pesos e Regras) ---
PESOS = {
    "urgencia": {"alta": 50, "media": 25, "baixa": 10},
    "capacidade_financeira": {"alta": 40, "media": 20, "baixa": 5},
    "bonus_tag_premium": 10  # Bônus para tags de alto valor
}

# --- 3. BANCO DE DADOS (Simulação) ---
estoque = [
    {"id": 1, "titulo": "Apto com Varanda Gourmet", "tags": ["varanda", "escritorio"], "preco": 450000},
    {"id": 2, "titulo": "Studio compacto", "tags": ["compacto"], "preco": 250000},
    {"id": 3, "titulo": "Cobertura Luxo", "tags": ["varanda", "piscina", "luxo"], "preco": 900000} # Adicionado 'luxo'
]

# --- 4. SCHEMA DE EXTRAÇÃO ---
class LeadScoring(BaseModel):
    motivo_mudanca: str = Field(description="Resumo do evento de vida do usuário")
    urgencia: str = Field(description="Classificação: alta, media ou baixa")
    capacidade_financeira: str = Field(description="Classificação: alta, media ou baixa")
    tags: List[str] = Field(description="Interesses específicos, ex: varanda, pet-friendly")

# --- 5. O CÉREBRO (Processamento Completo) ---
def processar_lead(texto_usuario):
    # A. Extração (IA) usando response_schema para robustez
    prompt = f"""
    Analise o texto: '{texto_usuario}'. Extraia os dados do lead conforme o schema JSON.

    Extraia apenas o JSON.
    """
    response = model.generate_content(
        prompt,
        generation_config={
            "response_mime_type": "application/json",
            "response_schema": LeadScoring,
        },
    )
    raw_json = response.text.replace("```json", "").replace("```", "").strip()
    dados = json.loads(raw_json)

    # B. Recomendação (Lógica)
    sugestoes = [i for i in estoque if any(tag in i['tags'] for tag in dados['tags'])]

    # C. Scoring (Matemática de Negócio)
    score = PESOS['urgencia'].get(dados['urgencia'], 0) + \
            PESOS['capacidade_financeira'].get(dados['capacidade_financeira'], 0)
    # Aplica bônus por tags
    for tag in dados['tags']:
        if tag in ['luxo', 'cobertura']: # Mantendo 'cobertura' para uso futuro
            score += PESOS['bonus_tag_premium']

    temperatura = "QUENTE" if score >= 80 else ("MORNO" if score >= 40 else "FRIO")

    # D. Saída (Dossiê) - Adaptado para o formato do usuário
    sugestoes_titulos = [s['titulo'] for s in sugestoes]
    dossie_string = f"Lead: {dados['motivo_mudanca']} | Sugestões: {sugestoes_titulos}"

    return {
        "status": "sucesso",
        "score": score,
        "temperatura": temperatura,
        "dossie": dossie_string
    }

# --- TESTE DO MVP ---
texto_teste = "Preciso de uma cobertura de luxo urgente, tenho orçamento alto."
resultado = processar_lead(texto_teste)
print(json.dumps(resultado, indent=2, ensure_ascii=False))



# --- CÉLULA DE TESTES ---
# Lista de cenários para validar seu sistema
testes = [
    "Estou só olhando, sem pressa, quero algo barato.",
    "Preciso de uma cobertura de luxo urgente, tenho orçamento alto e quero piscina.",
    "Tenho urgência para me mudar, preciso de um apto com varanda, orçamento médio."
]

print("Iniciando testes em lote...\n")

for t in testes:
    print(f"--- Testando: {t} ---")
    resultado = processar_lead(t)
    salvar_lead_csv(resultado, caminho_arquivo)
    print(f"Resultado: {resultado['temperatura']} | Score: {resultado['score']}\n")

print("Testes concluídos! Verifique o arquivo CSV criado no seu Google Drive na pasta 'MeusLeads'.")

"""### Testando a remoção de duplicatas"""

# Antes de remover, vamos adicionar alguns leads que provavelmente já existem para criar duplicatas
for _ in range(2):
    salvar_lead_csv(processar_lead("Estou só olhando, sem pressa, quero algo barato."), caminho_arquivo)
    salvar_lead_csv(processar_lead("Preciso de uma cobertura de luxo urgente, tenho orçamento alto e quero piscina."), caminho_arquivo)

print("Adicionadas algumas entradas duplicadas para teste.")

# Agora, remova as duplicatas
remover_duplicadas_csv(caminho_arquivo)

# Verifique o conteúdo do CSV após a remoção (opcional)
print("\nConteúdo do CSV após remoção de duplicatas:")
display(pd.read_csv(caminho_arquivo))